apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins-ns
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
  namespace: jenkins-ns
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling", "batch"]  
  resources: ["deployments", "services", "replicasets", "pods"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
  namespace: jenkins-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
