apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0t...
    server: https://...
  name: ...

contexts:
- context:
    cluster: ...
    user: ...
  name: 

users:
- name: ...
  user:
    token: 

current-context: ...
